/* ── 길눈 · 지역/장소 데이터 ──────────────────────────────────
   좌표는 근사값이며 동선 계산·지도 표시에만 사용한다.
   주차/요금/웨이팅 정보는 2025년 기준 참고용 — 방문 전 공식 채널 확인 필수.

   slot: am(오전) | lunch(점심) | pm(오후) | cafe(카페) | dinner(저녁) | night(밤)
   fit : solo | friends | couple | family
   parking.ok: true(수월) | 'hard'(어려움/공영 이용) | false(사실상 불가)          */

const REGIONS = [
  /* ───────────────────────── 서울 ───────────────────────── */
  {
    id: "seoul", name: "서울", en: "SEOUL",
    tagline: "궁궐의 아침부터 남산의 밤까지, 오래된 것과 새것이 겹치는 도시",
    landmark: "경복궁 · N서울타워",
    maxDays: 3, speed: 330,
    artPrompt: "Cinematic wide shot of Gyeongbokgung Palace with N Seoul Tower on Namsan mountain in the background at dusk, traditional Korean palace roof lines in the foreground, warm lantern light, indigo blue sky, photorealistic, 16:9",
    zones: [
      { name: "종로 · 북촌", theme: "궁궐과 한옥 골목을 걷는 날" },
      { name: "남산 · 명동", theme: "도심 전망과 옛 시장의 맛" },
      { name: "성수 · 잠실", theme: "숲과 카페, 하늘 위 전망" }
    ],
    places: [
      { id:"gbg", name:"경복궁", cat:"spot", zone:0, slot:"am", lat:37.5796, lng:126.9770, stay:100,
        desc:"조선의 법궁. 오전 수문장 교대식(10시)과 근정전·경회루 코스가 핵심.",
        fit:["family","couple","friends","solo"],
        parking:{ ok:"hard", note:"국립고궁박물관 주차장(유료) 이용, 주말 만차 잦음 — 3호선 경복궁역 도보 추천" },
        ticket:{ note:"성인 3,000원 · 한복 착용 시 무료 · 화요일 휴궁, 현장 발권 가능" },
        wait:null },
      { id:"bukchon", name:"북촌한옥마을", cat:"spot", zone:0, slot:"am", lat:37.5826, lng:126.9838, stay:70,
        desc:"경복궁과 창덕궁 사이 한옥 골목. 북촌 8경 포토스팟은 오전이 한산하다.",
        fit:["couple","friends","solo"],
        parking:{ ok:false, note:"마을 내 주차 불가 — 정독도서관·공영주차장 이용 후 도보" },
        ticket:null,
        wait:{ note:"거주지역이라 오전 10시~오후 5시 방문 권장(방문 시간제 운영)" } },
      { id:"tosokchon", name:"토속촌삼계탕", cat:"food", zone:0, slot:"lunch", lat:37.5776, lng:126.9717, stay:60,
        desc:"경복궁 서쪽 한옥에서 먹는 삼계탕. 외국인·현지인 모두 줄 서는 집.",
        fit:["family","friends","couple","solo"],
        parking:{ ok:"hard", note:"전용 주차 협소 — 인근 공영주차장 또는 도보 이동 권장" },
        ticket:null,
        wait:{ note:"피크(12~13시) 20~40분 대기, 회전은 빠른 편 — 오픈런 또는 11시대 방문 추천" } },
      { id:"onion", name:"어니언 안국", cat:"cafe", zone:0, slot:"cafe", lat:37.5789, lng:126.9855, stay:50,
        desc:"한옥을 개조한 베이커리 카페. 마당 툇마루 좌석과 팡도르가 시그니처.",
        fit:["couple","friends","solo"],
        parking:{ ok:false, note:"주차 불가 — 안국역 도보 1분" },
        ticket:null,
        wait:{ note:"주말 오후 대기 흔함, 좌석 회전 빠름" } },
      { id:"ikseon", name:"익선동 한옥거리", cat:"spot", zone:0, slot:"pm", lat:37.5720, lng:126.9903, stay:60,
        desc:"1920년대 한옥 골목이 카페·소품숍 거리로. 좁은 골목 산책 자체가 볼거리.",
        fit:["couple","friends"],
        parking:{ ok:false, note:"골목 주차 불가 — 종로3가역 4·6번 출구 도보" },
        ticket:null, wait:null },
      { id:"gwangjang", name:"광장시장", cat:"food", zone:0, slot:"dinner", lat:37.5701, lng:126.9996, stay:70,
        desc:"빈대떡·마약김밥·육회의 성지. 저녁 시간 먹자골목 분위기가 절정.",
        fit:["friends","family","solo"],
        parking:{ ok:"hard", note:"시장 공영주차장 있으나 협소 — 1호선 종로5가역 이용 권장" },
        ticket:null,
        wait:{ note:"유명 육회집(부촌육회 등)은 30분 이상 대기 — 테이블링 앱 원격 줄서기 지원" } },
      { id:"namsan", name:"N서울타워", cat:"spot", zone:1, slot:"night", lat:37.5512, lng:126.9882, stay:90,
        desc:"서울 야경의 정점. 케이블카 또는 남산 순환버스로 오른다.",
        fit:["couple","family","friends"],
        parking:{ ok:false, note:"타워 직접 주차 불가 — 남산공원 공영주차장 후 순환버스, 또는 명동역에서 케이블카" },
        ticket:{ note:"전망대 성인 21,000원 · 공식 홈페이지/네이버 예약 시 할인, 케이블카 왕복 15,000원 별도" },
        wait:{ note:"주말 저녁 케이블카 30분 이상 대기 — 일몰 1시간 전 도착 추천" } },
      { id:"mdkj", name:"명동교자", cat:"food", zone:1, slot:"lunch", lat:37.5626, lng:126.9855, stay:50,
        desc:"1966년부터 이어온 칼국수·만두 단일 메뉴 노포. 회전이 매우 빠르다.",
        fit:["family","friends","solo"],
        parking:{ ok:false, note:"주차 불가 — 명동 공영주차장 이용" },
        ticket:null,
        wait:{ note:"줄이 길어도 10~20분 내 입장하는 편(합석 문화)" } },
      { id:"namsangol", name:"남산골한옥마을", cat:"spot", zone:1, slot:"am", lat:37.5594, 	lng:126.9946, stay:70,
        desc:"남산 자락에 복원한 전통 한옥 다섯 채와 정원. 무료 입장에 한적하다.",
        fit:["family","couple","solo"],
        parking:{ ok:"hard", note:"전용 주차장 소규모(유료) — 충무로역 3·4번 출구 도보 5분 추천" },
        ticket:{ note:"무료 · 월요일 휴관" },
        wait:null },
      { id:"picnic", name:"피크닉(piknic)", cat:"cafe", zone:1, slot:"cafe", lat:37.5588, 	lng:126.9772, stay:60,
        desc:"회현동 언덕의 전시+카페 복합공간. 루프탑에서 남산타워가 정면으로 보인다.",
        fit:["couple","solo","friends"],
        parking:{ ok:false, note:"주차 공간 없음 — 회현역 도보 5분" },
        ticket:{ note:"카페는 무료, 전시 관람 시 별도 티켓(전시별 상이)" },
        wait:null },
      { id:"seoulforest", name:"서울숲", cat:"spot", zone:2, slot:"am", lat:37.5444, lng:127.0374, stay:80,
        desc:"메타세쿼이아 길과 사슴 방사장이 있는 도심 숲. 가을 은행나무길이 유명.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"공영주차장 넉넉(유료, 30분 1,050원 수준) — 주말 오후엔 대기 발생" },
        ticket:{ note:"무료" }, wait:null },
      { id:"daelim", name:"대림창고", cat:"cafe", zone:2, slot:"cafe", lat:37.5417, lng:127.0566, stay:60,
        desc:"성수동 붉은 벽돌 창고를 개조한 갤러리 카페. 성수 카페거리의 원조 격.",
        fit:["friends","couple"],
        parking:{ ok:false, note:"주차 불가 — 성수역 3번 출구 도보, 인근 공영주차장 이용" },
        ticket:null,
        wait:{ note:"주말 오후 입장 대기 있으나 공간이 넓어 회전 빠름" } },
      { id:"seongsu-gamja", name:"소문난성수감자탕", cat:"food", zone:2, slot:"lunch", lat:37.5447, lng:127.0561, stay:60,
        desc:"백년가게로 선정된 성수동 감자탕 노포. 점심 뼈해장국이 인기.",
        fit:["family","friends","solo"],
        parking:{ ok:"hard", note:"매장 앞 주차 협소 — 인근 유료주차장 이용" },
        ticket:null,
        wait:{ note:"점심 피크 15~30분 대기" } },
      { id:"seoulsky", name:"롯데월드타워 서울스카이", cat:"spot", zone:2, slot:"pm", lat:37.5125, lng:127.1025, stay:90,
        desc:"117~123층 전망대. 유리 바닥 스카이데크에서 서울 전경을 내려다본다.",
        fit:["family","couple","friends"],
        parking:{ ok:true, note:"롯데월드몰 주차장 이용(유료) — 전망대 이용 시 할인 등록" },
        ticket:{ note:"성인 31,000원 · 공식 앱/온라인 사전 예약 시 대기 없이 입장, 일몰 시간대 조기 매진 잦음" },
        wait:{ note:"현장 발권은 주말 30분 이상 — 온라인 예약 강력 추천" } },
      { id:"ttukseom", name:"뚝섬한강공원", cat:"spot", zone:2, slot:"night", lat:37.5297, lng:127.0668, stay:60,
        desc:"한강 야경과 야간 피크닉. 편의점 라면과 돗자리 대여가 하나의 코스.",
        fit:["friends","couple"],
        parking:{ ok:true, note:"한강공원 주차장(유료) — 여름 저녁 만차 주의" },
        ticket:{ note:"무료" }, wait:null }
    ]
  },

  /* ───────────────────────── 부산 ───────────────────────── */
  {
    id: "busan", name: "부산", en: "BUSAN",
    tagline: "산복도로의 골목과 광안대교의 밤, 바다를 끼고 도는 도시",
    landmark: "광안대교 · 해운대",
    maxDays: 3, speed: 380,
    artPrompt: "Gwangan Bridge glowing over the night sea of Busan, colorful hillside houses of Gamcheon village in the foreground, fishing boats, deep indigo and warm orange lights, cinematic, 16:9",
    zones: [
      { name: "원도심 · 영도", theme: "골목과 시장, 바다 절벽을 걷는 날" },
      { name: "해운대 · 광안리", theme: "해변 열차와 두 개의 바다" },
      { name: "기장 해안", theme: "바다 사찰과 해안 드라이브" }
    ],
    places: [
      { id:"gamcheon", name:"감천문화마을", cat:"spot", zone:0, slot:"am", lat:35.0975, lng:129.0106, stay:100,
        desc:"산비탈 계단식 파스텔 마을. 어린왕자 포토스팟은 오전이 줄이 짧다.",
        fit:["friends","couple","family"],
        parking:{ ok:"hard", note:"마을 초입 공영주차장 협소 — 토성역에서 마을버스(사하1-1) 추천" },
        ticket:{ note:"무료 · 스탬프 지도 2,000원(안내센터 구매)" },
        wait:{ note:"어린왕자 조형물 포토존 주말 20~30분 줄" } },
      { id:"jagalchi", name:"자갈치시장", cat:"food", zone:0, slot:"lunch", lat:35.0967, lng:129.0306, stay:70,
        desc:"부산 대표 수산시장. 1층에서 회를 떠서 2층 초장집에서 먹는 방식.",
        fit:["family","friends"],
        parking:{ ok:true, note:"시장 건물 주차타워(유료) — 구매 금액에 따라 할인" },
        ticket:null,
        wait:{ note:"흥정은 필수, 점심 피크엔 초장집 자리 대기" } },
      { id:"gukje", name:"국제시장 · 깡통시장", cat:"spot", zone:0, slot:"pm", lat:35.1010, lng:129.0288, stay:60,
        desc:"영화 '국제시장'의 그 시장. 씨앗호떡·비빔당면 등 길거리 간식 순례.",
        fit:["family","friends","solo"],
        parking:{ ok:"hard", note:"공영주차장 있으나 혼잡 — 자갈치에서 도보 이동 추천" },
        ticket:null, wait:null },
      { id:"huinnyeoul", name:"흰여울문화마을", cat:"spot", zone:0, slot:"pm", lat:35.0785, lng:129.0453, stay:70,
        desc:"영도 절벽 위 바닷가 골목. '변호인' 촬영지로, 해안 산책로가 백미.",
        fit:["couple","solo","friends"],
        parking:{ ok:"hard", note:"마을 주차 불가 — 절영해안산책로 공영주차장 후 도보" },
        ticket:null, wait:null },
      { id:"piarc", name:"피아크(P.ARK)", cat:"cafe", zone:0, slot:"cafe", lat:35.0912, lng:129.0679, stay:60,
        desc:"영도 조선소 뷰의 초대형 카페 겸 문화공간. 통유리 바다 전망.",
        fit:["friends","couple","family"],
        parking:{ ok:true, note:"건물 전용 주차장 보유(구매 시 할인)" },
        ticket:null, wait:null },
      { id:"choryang", name:"초량밀면", cat:"food", zone:0, slot:"dinner", lat:35.1163, lng:129.0400, stay:50,
        desc:"부산역 근처 밀면 노포. 냉밀면과 만두 조합이 정석.",
        fit:["solo","friends","family"],
        parking:{ ok:false, note:"주차 불가 — 부산역 주차장 이용 후 도보" },
        ticket:null,
        wait:{ note:"식사 시간대 줄 서지만 회전 빠름(15분 내외)" } },
      { id:"haeundae", name:"해운대해수욕장", cat:"spot", zone:1, slot:"am", lat:35.1587, lng:129.1604, stay:70,
        desc:"부산의 얼굴. 아침 백사장 산책과 동백섬 누리마루 코스.",
        fit:["family","couple","friends","solo"],
        parking:{ ok:"hard", note:"해수욕장 공영주차장 여름철 만차 — 대중교통 또는 호텔 주차 연계 추천" },
        ticket:{ note:"무료" }, wait:null },
      { id:"blueline", name:"해운대 블루라인파크", cat:"spot", zone:1, slot:"pm", lat:35.1592, lng:129.1755, stay:100,
        desc:"미포~송정 해안을 달리는 해변열차와 스카이캡슐. 왼쪽 좌석이 바다 뷰.",
        fit:["couple","family","friends"],
        parking:{ ok:true, note:"미포정거장 전용 주차장(유료)" },
        ticket:{ note:"해변열차 자유석 왕복 16,000원, 스카이캡슐 2인 편도 39,000원~ — 공식 홈페이지 사전 예약 필수(주말 매진 잦음)" },
        wait:{ note:"현장 발권 시 원하는 시간대 매진 가능 — 예약 후 QR 입장" } },
      { id:"haeridan", name:"해리단길", cat:"spot", zone:1, slot:"pm", lat:35.1637, lng:129.1591, stay:60,
        desc:"옛 해운대역 뒤 철길 마을이 변한 골목상권. 소품숍과 브런치집 밀집.",
        fit:["couple","friends"],
        parking:{ ok:false, note:"골목 주차 불가 — 해운대역 공영주차장 후 도보" },
        ticket:null, wait:null },
      { id:"amso", name:"해운대암소갈비집", cat:"food", zone:1, slot:"dinner", lat:35.1663, lng:129.1602, stay:80,
        desc:"1964년 개업한 부산 대표 갈비집. 가격대가 있지만 특별한 저녁으로 손색없다.",
        fit:["family","couple"],
        parking:{ ok:true, note:"전용 주차장·발레 지원" },
        ticket:null,
        wait:{ note:"저녁 웨이팅 김 — 전화 예약 가능, 예약 추천" } },
      { id:"gwangalli", name:"광안리해수욕장", cat:"spot", zone:1, slot:"night", lat:35.1532, lng:129.1186, stay:70,
        desc:"광안대교 야경의 명당. 토요일 밤 드론쇼(시즌 운영)가 열린다.",
        fit:["couple","friends"],
        parking:{ ok:"hard", note:"해변 공영주차장 저녁 만차 — 금련산역 도보 10분 추천" },
        ticket:{ note:"무료 · 드론쇼 일정은 수영구청 공지 확인" },
        wait:null },
      { id:"millac", name:"밀락더마켓", cat:"food", zone:1, slot:"lunch", lat:35.1571, lng:129.1266, stay:70,
        desc:"광안리 끝 복합 푸드홀. 바다 계단 좌석에서 광안대교를 보며 먹는다.",
        fit:["friends","couple","family"],
        parking:{ ok:true, note:"건물 주차장 보유(유료, 구매 할인)" },
        ticket:null,
        wait:{ note:"인기 매장은 개별 줄 — 자리 먼저 확보 후 주문 추천" } },
      { id:"yonggungsa", name:"해동용궁사", cat:"spot", zone:2, slot:"am", lat:35.1884, lng:129.2233, stay:80,
        desc:"바다 절벽 위에 지어진 사찰. 일출 명소라 이른 오전이 가장 좋다.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"사찰 입구 주차장(유료) — 주말 오전 10시 이후 혼잡" },
        ticket:{ note:"무료" },
        wait:{ note:"주말 낮 진입로 정체 — 오전 9시 전 도착 추천" } },
      { id:"waveon", name:"웨이브온 커피", cat:"cafe", zone:2, slot:"cafe", lat:35.3283, lng:129.2585, stay:70,
        desc:"기장 임랑해변의 건축상 수상 오션뷰 카페. 루프탑 스탠딩석이 명당.",
        fit:["couple","friends"],
        parking:{ ok:true, note:"전용 주차장 보유 — 주말 오후 만차 시 인근 공영 이용" },
        ticket:null,
        wait:{ note:"주말 좌석 경쟁 치열 — 오픈 직후 또는 평일 추천" } },
      { id:"gijang-crab", name:"기장 곰장어·대게 거리", cat:"food", zone:2, slot:"dinner", lat:35.2445, lng:129.2222, stay:80,
        desc:"기장시장 일대 곰장어 짚불구이와 대게. 시세는 방문 전 흥정 필수.",
        fit:["family","friends"],
        parking:{ ok:"hard", note:"기장시장 공영주차장 이용(협소)" },
        ticket:null,
        wait:{ note:"저녁 성수기 대기 — 시장 내 여러 집 비교 후 착석" } },
      { id:"osiria", name:"롯데월드 어드벤처 부산", cat:"spot", zone:2, slot:"pm", lat:35.1959, lng:129.2131, stay:180,
        desc:"오시리아 관광단지의 테마파크. 아이 동반 가족 코스로 반나절.",
        fit:["family","friends"],
        parking:{ ok:true, note:"대형 주차타워 보유(유료)" },
        ticket:{ note:"종합이용권 성인 47,000원~ — 공식 앱 사전 구매 시 할인·매직패스 별도" },
        wait:{ note:"인기 어트랙션 60분 이상 — 앱에서 대기시간 확인" } }
    ]
  },

  /* ───────────────────────── 제주 ───────────────────────── */
  {
    id: "jeju", name: "제주", en: "JEJU",
    tagline: "오름과 현무암 바다, 하루마다 다른 바람이 부는 섬",
    landmark: "성산일출봉 · 협재 바다",
    maxDays: 3, speed: 620,
    artPrompt: "Seongsan Ilchulbong tuff cone rising over emerald sea at sunrise, black basalt stone walls and canola flower fields in foreground, haenyeo diver silhouette, soft morning light, cinematic, 16:9",
    zones: [
      { name: "동부 · 성산", theme: "일출봉과 해안도로, 당근밭 사이 카페" },
      { name: "서부 · 한림", theme: "에메랄드 바다와 차밭" },
      { name: "남부 · 서귀포", theme: "폭포와 미술 골목, 중문의 밤" }
    ],
    places: [
      { id:"seongsan", name:"성산일출봉", cat:"spot", zone:0, slot:"am", lat:33.4587, lng:126.9425, stay:100,
        desc:"유네스코 세계자연유산 화산체. 정상까지 왕복 50분, 오전 역광이 없다.",
        fit:["family","friends","couple","solo"],
        parking:{ ok:true, note:"대형 공영주차장 무료 — 성수기 오전 10시 이후 혼잡" },
        ticket:{ note:"성인 5,000원 · 현장 발권, 일출 시간대는 새벽 개장" },
        wait:null },
      { id:"gwangchigi", name:"광치기해변", cat:"spot", zone:0, slot:"am", lat:33.4506, lng:126.9195, stay:40,
        desc:"썰물 때 이끼 낀 용암 지질이 드러나는 해변. 일출봉을 배경으로 한 인생샷 명소.",
        fit:["couple","solo","friends"],
        parking:{ ok:true, note:"해변 앞 무료 주차장" },
        ticket:{ note:"무료 · 물때(간조) 시간 확인 후 방문" }, wait:null },
      { id:"seopjikoji", name:"섭지코지", cat:"spot", zone:0, slot:"pm", lat:33.4240, lng:126.9280, stay:80,
        desc:"해안 절벽 산책로와 등대. 유채꽃 시즌(3~4월)이 절정.",
        fit:["couple","family"],
        parking:{ ok:true, note:"주차장 유료(승용 1,000원)" },
        ticket:{ note:"산책로 무료" }, wait:null },
      { id:"gasiabang", name:"가시아방국수", cat:"food", zone:0, slot:"lunch", lat:33.4326, lng:126.9080, stay:60,
        desc:"고기국수와 돔베고기 세트가 대표. 성산 일대에서 가장 줄이 긴 국숫집.",
        fit:["family","friends","solo","couple"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null,
        wait:{ note:"피크 30~60분 — 캐치테이블 원격 줄서기 등록 후 근처 관광 추천" } },
      { id:"woljeongri", name:"월정리해변", cat:"spot", zone:0, slot:"pm", lat:33.5560, lng:126.7959, stay:50,
        desc:"에메랄드빛 바다와 카페거리. 해안도로 드라이브 코스의 중심.",
        fit:["friends","couple"],
        parking:{ ok:"hard", note:"공영주차장 협소, 성수기 갓길 단속 주의" },
        ticket:{ note:"무료" }, wait:null },
      { id:"myeongjin", name:"명진전복", cat:"food", zone:0, slot:"dinner", lat:33.5541, lng:126.8319, stay:70,
        desc:"구좌 해안도로의 전복돌솥밥 명가. 창가석에서 바다를 보며 먹는다.",
        fit:["family","couple"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null,
        wait:{ note:"대기 김 — 오픈 시간(9:30) 직후나 브레이크타임 직후 방문 추천, 화요일 휴무" } },
      { id:"orn", name:"카페 오른", cat:"cafe", zone:0, slot:"cafe", lat:33.4680, lng:126.9310, stay:60,
        desc:"성산일출봉이 통창으로 보이는 오션뷰 카페. 루프탑 명당은 이른 오후에.",
        fit:["couple","friends"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null, wait:{ note:"성수기 주말 좌석 대기" } },
      { id:"hyeopjae", name:"협재해수욕장", cat:"spot", zone:1, slot:"am", lat:33.3940, lng:126.2396, stay:80,
        desc:"비양도를 마주 보는 제주 서쪽 대표 해변. 수심이 얕아 아이와도 좋다.",
        fit:["family","couple","friends"],
        parking:{ ok:true, note:"공영주차장 무료 — 여름 성수기 오전 일찍 도착 추천" },
        ticket:{ note:"무료" }, wait:null },
      { id:"hallimpark", name:"한림공원", cat:"spot", zone:1, slot:"pm", lat:33.3893, lng:126.2394, stay:90,
        desc:"협재굴·쌍용굴과 야자수 길이 있는 노포 관광지. 계절 꽃축제가 이어진다.",
        fit:["family","solo"],
        parking:{ ok:true, note:"무료 주차장" },
        ticket:{ note:"성인 15,000원 · 현장/온라인 발권" }, wait:null },
      { id:"osulloc", name:"오설록 티뮤지엄", cat:"spot", zone:1, slot:"pm", lat:33.3058, lng:126.2895, stay:70,
        desc:"녹차밭 한가운데의 티 뮤지엄. 옆 이니스프리하우스까지 세트 코스.",
        fit:["couple","family","friends","solo"],
        parking:{ ok:true, note:"무료 대형 주차장" },
        ticket:{ note:"입장 무료" },
        wait:{ note:"녹차 아이스크림 줄 주말 20분 내외" } },
      { id:"hanrim-kal", name:"한림칼국수 한림본점", cat:"food", zone:1, slot:"lunch", lat:33.4139, lng:126.2626, stay:50,
        desc:"보말칼국수와 보말죽. 아침 일찍부터 여는 서부 대표 로컬 식당.",
        fit:["family","solo","friends"],
        parking:{ ok:"hard", note:"매장 앞 협소 — 한림항 공영주차장 이용" },
        ticket:null,
        wait:{ note:"피크 대기 있음, 회전 빠름 — 재료 소진 시 조기 마감" } },
      { id:"anthracite", name:"앤트러사이트 제주한림", cat:"cafe", zone:1, slot:"cafe", lat:33.4133, lng:126.2687, stay:60,
        desc:"옛 전분공장을 개조한 로스터리. 폐공장의 기둥과 빛이 만드는 공간감.",
        fit:["solo","couple","friends"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null, wait:null },
      { id:"cheonjiyeon", name:"천지연폭포", cat:"spot", zone:2, slot:"am", lat:33.2452, lng:126.5544, stay:60,
        desc:"서귀포 도심의 폭포. 야간 개장(22시까지)이라 밤 산책도 가능.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"무료 주차장" },
        ticket:{ note:"성인 2,000원 · 현장 발권" }, wait:null },
      { id:"jeongbang", name:"정방폭포", cat:"spot", zone:2, slot:"am", lat:33.2447, lng:126.5710, stay:50,
        desc:"바다로 직접 떨어지는 국내 유일의 해안 폭포.",
        fit:["family","friends","solo"],
        parking:{ ok:true, note:"주차장 보유(협소) — 천지연과 묶어 오전 방문 추천" },
        ticket:{ note:"성인 2,000원" }, wait:null },
      { id:"lee-js", name:"이중섭거리 · 서귀포매일올레시장", cat:"spot", zone:2, slot:"pm", lat:33.2477, lng:126.5629, stay:70,
        desc:"화가 이중섭의 골목과 올레시장. 마농치킨·꽁치김밥 등 시장 간식 순례.",
        fit:["friends","family","solo"],
        parking:{ ok:"hard", note:"시장 공영주차장 혼잡 — 이중섭거리 뒤편 공영 이용" },
        ticket:null, wait:null },
      { id:"saekdal", name:"색달식당 중문본점", cat:"food", zone:2, slot:"dinner", lat:33.2500, lng:126.4180, stay:70,
        desc:"통갈치조림의 대명사. 양이 많아 2인 이상 방문에 적합.",
        fit:["family","couple"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null,
        wait:{ note:"저녁 예약 권장(전화 예약 가능)" } },
      { id:"oneandonly", name:"원앤온리", cat:"cafe", zone:2, slot:"cafe", lat:33.2377, lng:126.3907, stay:60,
        desc:"산방산을 등지고 황우치해변을 마주한 대형 카페. 야외 테라스가 명당.",
        fit:["couple","friends"],
        parking:{ ok:true, note:"전용 주차장 보유 — 주말 만차 시 대기" },
        ticket:null,
        wait:{ note:"주말 오후 좌석 경쟁 — 오전 방문 추천" } }
    ]
  },

  /* ───────────────────────── 경주 ───────────────────────── */
  {
    id: "gyeongju", name: "경주", en: "GYEONGJU",
    tagline: "고분 사이로 해가 지는, 도시 전체가 노천 박물관",
    landmark: "첨성대 · 불국사",
    maxDays: 2, speed: 480,
    artPrompt: "Cheomseongdae observatory and grassy royal tomb mounds of Gyeongju under a pink sunset sky, cherry blossom petals in the air, warm hanok village lights in the distance, cinematic, 16:9",
    zones: [
      { name: "시내 · 황리단길", theme: "고분과 한옥 골목, 달빛의 동궁" },
      { name: "불국사 · 보문", theme: "천년 사찰과 호수의 오후" }
    ],
    places: [
      { id:"daereungwon", name:"대릉원 · 천마총", cat:"spot", zone:0, slot:"am", lat:35.8381, lng:129.2114, stay:80,
        desc:"거대한 신라 고분 사이를 걷는 공원. 목련 포토스팟(3월 말)이 유명.",
        fit:["family","couple","friends","solo"],
        parking:{ ok:true, note:"대릉원 공영주차장(유료) — 황리단길과 공유라 주말 혼잡" },
        ticket:{ note:"대릉원 무료 개방 · 천마총 내부 관람 무료" }, wait:null },
      { id:"cheomseongdae", name:"첨성대", cat:"spot", zone:0, slot:"pm", lat:35.8347, lng:129.2190, stay:40,
        desc:"동양에서 가장 오래된 천문대. 주변 꽃밭(계절별)과 함께 산책 코스.",
        fit:["family","couple","solo"],
        parking:{ ok:"hard", note:"전용 주차장 없음 — 대릉원 주차 후 도보 10분" },
        ticket:{ note:"무료" }, wait:null },
      { id:"donggung", name:"동궁과 월지(안압지)", cat:"spot", zone:0, slot:"night", lat:35.8347, lng:129.2265, stay:70,
        desc:"신라 별궁 연못의 야경. 해 진 직후 '매직아워'가 최고의 촬영 시간.",
        fit:["couple","family","friends"],
        parking:{ ok:true, note:"전용 주차장(유료) — 야간 진입 차량 몰림" },
        ticket:{ note:"성인 3,000원 · 현장 발권, 야간(22시까지) 개장" },
        wait:{ note:"일몰 직후 매표 줄 — 일몰 30분 전 도착 추천" } },
      { id:"hwangridan", name:"황리단길", cat:"spot", zone:0, slot:"pm", lat:35.8370, lng:129.2100, stay:70,
        desc:"한옥 상점 거리. 십원빵·경주빵 등 간식과 소품숍 순례.",
        fit:["friends","couple"],
        parking:{ ok:"hard", note:"거리 주차 불가 — 대릉원/공영주차장 후 도보" },
        ticket:null, wait:null },
      { id:"gyori", name:"교리김밥", cat:"food", zone:0, slot:"lunch", lat:35.8331, lng:129.2107, stay:40,
        desc:"계란 지단을 가득 넣은 김밥 단일 메뉴 노포. 경주 웨이팅 1순위.",
        fit:["solo","friends","family"],
        parking:{ ok:"hard", note:"매장 주차 협소 — 교촌마을 공영주차장 이용" },
        ticket:null,
        wait:{ note:"주말 1시간 이상 — 오픈(8:30) 직후 방문 또는 포장 추천, 재료 소진 시 마감" } },
      { id:"dosol", name:"도솔마을", cat:"food", zone:0, slot:"dinner", lat:35.8355, lng:129.2125, stay:70,
        desc:"한옥에서 먹는 정갈한 한상차림. 황리단길에서 가성비 좋은 한식 저녁.",
        fit:["family","couple"],
        parking:{ ok:"hard", note:"인근 공영주차장 이용" },
        ticket:null,
        wait:{ note:"저녁 대기 있음 — 대기 명부 작성 후 근처 산책" } },
      { id:"hwangnam", name:"황남빵 본점", cat:"cafe", zone:0, slot:"cafe", lat:35.8390, lng:129.2153, stay:30,
        desc:"1939년부터 이어온 경주 대표 팥빵. 갓 구운 빵을 현장에서.",
        fit:["family","solo"],
        parking:{ ok:true, note:"본점 전용 주차장 보유" },
        ticket:null,
        wait:{ note:"명절·주말 구매 줄 — 회전 빠름" } },
      { id:"eomeoeoma", name:"어마어마 카페", cat:"cafe", zone:0, slot:"cafe", lat:35.8362, lng:129.2085, stay:50,
        desc:"고분 뷰 통창의 황리단길 대표 카페. 2층 창가 자리가 명당.",
        fit:["couple","friends"],
        parking:{ ok:false, note:"주차 불가 — 도보 접근" },
        ticket:null,
        wait:{ note:"주말 오후 좌석 대기" } },
      { id:"bulguksa", name:"불국사", cat:"spot", zone:1, slot:"am", lat:35.7900, lng:129.3320, stay:100,
        desc:"석가탑·다보탑의 유네스코 세계유산. 오전의 고요함이 다르다.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"대형 주차장(승용 1,000원)" },
        ticket:{ note:"2023년부터 입장료 무료화 · 문화재 구역 통제 시간 확인" }, wait:null },
      { id:"seokguram", name:"석굴암", cat:"spot", zone:1, slot:"am", lat:35.7947, lng:129.3475, stay:60,
        desc:"토함산 중턱의 석굴 본존불. 불국사에서 차로 15분, 산길 드라이브.",
        fit:["family","solo","couple"],
        parking:{ ok:true, note:"석굴암 주차장(승용 2,000원)" },
        ticket:{ note:"무료 · 굴 내부는 유리 보호막 너머 관람" }, wait:null },
      { id:"bomun", name:"보문호반길", cat:"spot", zone:1, slot:"pm", lat:35.8420, lng:129.2820, stay:70,
        desc:"벚꽃 명소 보문호 둘레길. 자전거·오리배 대여로 호수 한 바퀴.",
        fit:["family","couple","friends"],
        parking:{ ok:true, note:"보문관광단지 무료 주차장 다수" },
        ticket:{ note:"산책 무료 · 오리배 등 별도 요금" }, wait:null },
      { id:"milkbook", name:"밀크북 경주", cat:"cafe", zone:1, slot:"cafe", lat:35.8440, lng:129.2860, stay:60,
        desc:"보문호숫가의 서점+베이커리 카페. 호수 뷰 테라스가 있다.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null, wait:null },
      { id:"ssambap", name:"이풍녀 구로쌈밥", cat:"food", zone:1, slot:"lunch", lat:35.8408, lng:129.2103, stay:60,
        desc:"대릉원 앞 쌈밥거리의 원조 격. 불고기 쌈밥 한상.",
        fit:["family","friends"],
        parking:{ ok:"hard", note:"쌈밥거리 공용 주차 협소 — 대릉원 주차장 이용" },
        ticket:null,
        wait:{ note:"점심 피크 대기 있음" } }
    ]
  },

  /* ───────────────────────── 강릉 ───────────────────────── */
  {
    id: "gangneung", name: "강릉", en: "GANGNEUNG",
    tagline: "솔숲 너머 바다, 커피 향으로 아침을 여는 동해안",
    landmark: "경포 바다 · 안목 커피거리",
    maxDays: 3, speed: 520,
    artPrompt: "Sunrise over the East Sea at Gyeongpo beach in Gangneung, pine tree silhouettes, a warm cup of hand-drip coffee in the foreground, gulls, soft pastel morning sky, cinematic, 16:9",
    zones: [
      { name: "경포 · 초당", theme: "솔숲 바다와 순두부 마을" },
      { name: "시내 · 안목", theme: "시장의 맛과 커피거리" },
      { name: "주문진", theme: "항구의 아침과 드라마 촬영지" }
    ],
    places: [
      { id:"ojukheon", name:"오죽헌", cat:"spot", zone:0, slot:"am", lat:37.7793, lng:128.8785, stay:70,
        desc:"신사임당과 율곡 이이의 생가. 검은 대나무 숲길이 고즈넉하다.",
        fit:["family","solo"],
        parking:{ ok:true, note:"무료 주차장" },
        ticket:{ note:"성인 3,000원 · 현장 발권" }, wait:null },
      { id:"gyeongpo", name:"경포해변 · 경포호", cat:"spot", zone:0, slot:"am", lat:37.8057, lng:128.9080, stay:70,
        desc:"강릉 대표 백사장과 호수 산책로. 솔숲 자전거길이 이어진다.",
        fit:["family","couple","friends"],
        parking:{ ok:true, note:"해변 공영주차장 다수(성수기 유료)" },
        ticket:{ note:"무료" }, wait:null },
      { id:"toenmaru", name:"툇마루", cat:"food", zone:0, slot:"lunch", lat:37.7877, lng:128.9128, stay:60,
        desc:"들기름 얹은 초당순두부의 대표 주자. 강릉 웨이팅 최상위권.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"전용 주차장 보유(협소) — 초당마을 공영 병행" },
        ticket:null,
        wait:{ note:"주말 1시간 이상 — 오픈(7시) 직후 아침 식사로 방문 추천, 브레이크타임 주의" } },
      { id:"sundubu-gelato", name:"순두부젤라또 1호점", cat:"cafe", zone:0, slot:"cafe", lat:37.7901, lng:128.9142, stay:30,
        desc:"초당순두부로 만든 젤라또. 식후 디저트 코스로 정석.",
        fit:["friends","family","couple"],
        parking:{ ok:"hard", note:"매장 앞 협소 — 초당마을 공영주차장 도보" },
        ticket:null, wait:{ note:"주말 구매 줄 10~20분" } },
      { id:"gangmun", name:"강문해변", cat:"spot", zone:0, slot:"pm", lat:37.7907, lng:128.9166, stay:50,
        desc:"경포 옆 아담한 해변. 방사탑과 오브제 포토스팟이 많다.",
        fit:["couple","friends"],
        parking:{ ok:"hard", note:"해변 앞 주차 협소 — 카페 이용 주차 병행" },
        ticket:{ note:"무료" }, wait:null },
      { id:"jungang", name:"강릉중앙시장", cat:"food", zone:1, slot:"lunch", lat:37.7550, lng:128.8970, stay:70,
        desc:"닭강정·오징어순대·어묵크로켓 먹거리 순례. 2층 회센터도 인기.",
        fit:["friends","family","solo"],
        parking:{ ok:true, note:"시장 공영주차타워(첫 30분 무료 수준) — 주말 대기" },
        ticket:null,
        wait:{ note:"유명 닭강정집 줄 20~30분" } },
      { id:"anmok", name:"안목해변 커피거리", cat:"cafe", zone:1, slot:"cafe", lat:37.7717, lng:128.9474, stay:70,
        desc:"강릉 커피의 시작점. 바다를 정면으로 둔 카페가 줄지어 있다.",
        fit:["couple","solo","friends"],
        parking:{ ok:"hard", note:"공영주차장 있으나 주말 만차 — 오전 방문 추천" },
        ticket:null, wait:null },
      { id:"terarosa", name:"테라로사 커피공장", cat:"cafe", zone:1, slot:"pm", lat:37.7031, lng:128.8850, stay:70,
        desc:"구정면 산자락의 로스팅 공장 본점. 스페셜티 커피의 성지.",
        fit:["solo","couple"],
        parking:{ ok:true, note:"넓은 전용 주차장" },
        ticket:null, wait:{ note:"주말 주문 줄 있음, 좌석 넉넉" } },
      { id:"wolhwa", name:"월화거리", cat:"spot", zone:1, slot:"pm", lat:37.7562, lng:128.8990, stay:50,
        desc:"폐철길을 걷기 좋은 거리로 만든 도심 산책로. 중앙시장과 이어진다.",
        fit:["friends","solo"],
        parking:{ ok:"hard", note:"중앙시장 주차타워 공유" },
        ticket:{ note:"무료" }, wait:null },
      { id:"haslla", name:"하슬라아트월드", cat:"spot", zone:1, slot:"am", lat:37.7079, lng:129.0139, stay:90,
        desc:"바닷가 절벽의 야외 조각공원 겸 미술관. 바다 위 산책로가 압권.",
        fit:["couple","family"],
        parking:{ ok:true, note:"무료 주차장" },
        ticket:{ note:"성인 15,000원 · 현장/온라인 발권" }, wait:null },
      { id:"jumunjin", name:"주문진항 · 회센터", cat:"food", zone:2, slot:"lunch", lat:37.8930, lng:128.8310, stay:80,
        desc:"동해안 최대 어시장. 오징어·대게 철에는 새벽 경매 구경도 가능.",
        fit:["family","friends"],
        parking:{ ok:true, note:"항구 공영주차장" },
        ticket:null,
        wait:{ note:"횟집은 흥정 후 초장집 이동 방식 — 주말 점심 혼잡" } },
      { id:"hyangho", name:"향호해변 BTS 버스정류장", cat:"spot", zone:2, slot:"pm", lat:37.8977, lng:128.8180, stay:40,
        desc:"BTS 'You Never Walk Alone' 앨범 재킷 촬영지를 재현한 포토스팟.",
        fit:["friends","couple","solo"],
        parking:{ ok:true, note:"해변 무료 주차장" },
        ticket:{ note:"무료" },
        wait:{ note:"촬영 줄이 생기는 주말 오후 — 오전 추천" } },
      { id:"yeongjin", name:"영진해변 방파제", cat:"spot", zone:2, slot:"pm", lat:37.9046, lng:128.8237, stay:40,
        desc:"드라마 '도깨비' 촬영지. 방파제 위 인생샷 한 장을 위한 곳.",
        fit:["couple","friends"],
        parking:{ ok:"hard", note:"갓길 협소 — 인근 공영주차장 도보" },
        ticket:{ note:"무료" },
        wait:{ note:"포토스팟 줄서기(주말 20분 내외)" } },
      { id:"bosanmot", name:"엄지네포장마차 본점", cat:"food", zone:0, slot:"dinner", lat:37.7714, lng:128.9059, stay:70,
        desc:"꼬막무침비빔밥의 원조. 저녁엔 술 한잔 코스로도 좋다.",
        fit:["friends","family"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null,
        wait:{ note:"저녁 대기 김 — 테이블링 원격 줄서기 지원" } }
    ]
  },

  /* ───────────────────────── 전주 ───────────────────────── */
  {
    id: "jeonju", name: "전주", en: "JEONJU",
    tagline: "한옥 처마 아래, 한 끼가 예술이 되는 미식의 수도",
    landmark: "전주한옥마을 · 전동성당",
    maxDays: 2, speed: 380,
    artPrompt: "Traditional hanok village rooftops of Jeonju at golden hour, Jeondong Catholic cathedral's romanesque dome in the background, people in hanbok walking a stone alley, warm lantern glow, cinematic, 16:9",
    zones: [
      { name: "한옥마을", theme: "처마 밑 골목과 비빔밥 한 그릇" },
      { name: "남부시장 · 객리단길", theme: "야시장의 밤과 오래된 다방" }
    ],
    places: [
      { id:"gyeonggijeon", name:"경기전", cat:"spot", zone:0, slot:"am", lat:35.8152, lng:127.1500, stay:70,
        desc:"태조 이성계의 어진을 모신 곳. 대나무 숲길과 한복 스냅 1번지.",
        fit:["family","couple","friends"],
        parking:{ ok:"hard", note:"한옥마을 공영주차장(유료) 이용 후 도보 — 주말 오전 일찍 주차 추천" },
        ticket:{ note:"성인 3,000원 · 한복 착용 시 할인, 현장 발권" }, wait:null },
      { id:"jeondong", name:"전동성당", cat:"spot", zone:0, slot:"am", lat:35.8135, lng:127.1490, stay:40,
        desc:"로마네스크 양식의 붉은 벽돌 성당. 경기전 맞은편이라 세트 코스.",
        fit:["couple","family","solo"],
        parking:{ ok:false, note:"성당 주차 불가 — 도보 방문" },
        ticket:{ note:"무료(미사 시간 내부 관람 제한)" }, wait:null },
      { id:"omokdae", name:"오목대", cat:"spot", zone:0, slot:"pm", lat:35.8145, lng:127.1546, stay:40,
        desc:"한옥마을 지붕 물결을 한눈에 내려다보는 언덕. 노을 시간 추천.",
        fit:["couple","solo","friends"],
        parking:{ ok:false, note:"도보 접근(계단길)" },
        ticket:{ note:"무료" }, wait:null },
      { id:"jaman", name:"자만벽화마을", cat:"spot", zone:0, slot:"pm", lat:35.8158, lng:127.1570, stay:50,
        desc:"오목대 건너 언덕의 벽화 골목. 한옥마을 뷰 포인트가 곳곳에.",
        fit:["friends","couple"],
        parking:{ ok:false, note:"골목 주차 불가 — 오목대에서 육교로 도보" },
        ticket:null, wait:null },
      { id:"hasukyoung", name:"하숙영가마솥비빔밥", cat:"food", zone:0, slot:"lunch", lat:35.8156, lng:127.1516, stay:60,
        desc:"가마솥에 비벼 나오는 전주비빔밥. 미쉐린 가이드에도 오른 집.",
        fit:["family","couple","solo"],
        parking:{ ok:"hard", note:"전용 주차 없음 — 공영주차장 도보" },
        ticket:null,
        wait:{ note:"점심 30분~1시간 — 오픈(11시) 전 대기 명부 작성 추천" } },
      { id:"veteran", name:"베테랑칼국수", cat:"food", zone:0, slot:"dinner", lat:35.8150, lng:127.1553, stay:50,
        desc:"들깨와 계란이 풀린 걸쭉한 칼국수. 1977년부터 한 자리.",
        fit:["solo","friends","family"],
        parking:{ ok:false, note:"주차 불가 — 도보 방문" },
        ticket:null,
        wait:{ note:"줄이 길지만 회전 빠름(15~20분)" } },
      { id:"pnb", name:"PNB 풍년제과 본점", cat:"cafe", zone:0, slot:"cafe", lat:35.8158, lng:127.1478, stay:30,
        desc:"전주 초코파이 원조. 선물용 박스는 오후 품절이 잦다.",
        fit:["family","solo"],
        parking:{ ok:false, note:"주차 불가 — 도보 방문" },
        ticket:null, wait:{ note:"주말 계산 줄 — 회전 빠름" } },
      { id:"jeonmang", name:"카페 전망", cat:"cafe", zone:0, slot:"cafe", lat:35.8143, lng:127.1535, stay:60,
        desc:"한옥마을 지붕이 파노라마로 보이는 루프탑 카페. 노을 명당.",
        fit:["couple","friends"],
        parking:{ ok:false, note:"주차 불가 — 도보 방문" },
        ticket:null,
        wait:{ note:"노을 시간대 루프탑 자리 경쟁" } },
      { id:"nambu", name:"남부시장 야시장", cat:"spot", zone:1, slot:"night", lat:35.8115, lng:127.1470, stay:80,
        desc:"금·토 저녁에 열리는 청년몰 야시장. 먹거리 매대가 골목을 채운다.",
        fit:["friends","couple","family"],
        parking:{ ok:true, note:"시장 공영주차장(유료)" },
        ticket:{ note:"무료 · 야시장은 금·토 18시~ 운영(동절기 단축)" },
        wait:{ note:"인기 매대 줄 10~20분" } },
      { id:"hyundaiok", name:"현대옥 남부시장점", cat:"food", zone:1, slot:"lunch", lat:35.8117, lng:127.1468, stay:40,
        desc:"콩나물국밥의 표준. 수란에 국물 한 숟갈 넣어 먹는 게 정석.",
        fit:["solo","family","friends"],
        parking:{ ok:true, note:"남부시장 공영주차장 이용" },
        ticket:null,
        wait:{ note:"아침·점심 회전 빠름 — 대기 짧음" } },
      { id:"gaekridan", name:"객리단길", cat:"spot", zone:1, slot:"pm", lat:35.8185, lng:127.1430, stay:60,
        desc:"객사 옆 골목상권. 레트로 감성 카페와 술집이 이어진다.",
        fit:["friends","couple"],
        parking:{ ok:"hard", note:"공영주차장 이용 후 도보" },
        ticket:null, wait:null },
      { id:"samyang", name:"삼양다방", cat:"cafe", zone:1, slot:"cafe", lat:35.8168, lng:127.1450, stay:40,
        desc:"1952년 개업, 현존 최고(最古) 다방. 쌍화차와 계란 동동 옛 커피.",
        fit:["solo","family","couple"],
        parking:{ ok:false, note:"주차 불가 — 도보 방문" },
        ticket:null, wait:null },
      { id:"deokjin", name:"덕진공원", cat:"spot", zone:1, slot:"am", lat:35.8442, lng:127.1194, stay:60,
        desc:"여름 연꽃으로 뒤덮이는 호수 공원. 연화교 위 산책이 백미.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"공원 주차장(유료)" },
        ticket:{ note:"무료" }, wait:null }
    ]
  }
,

  /* ───────────────────────── 여수 ───────────────────────── */
  {
    id: "yeosu", name: "여수", en: "YEOSU",
    tagline: "밤바다의 낭만과 게장 한 상, 케이블카로 건너는 바다",
    landmark: "여수 밤바다 · 향일암",
    maxDays: 2, speed: 450,
    artPrompt: "Yeosu night sea with cable car cabins crossing over the water, Dolsan bridge lit in colors, romantic pocha street lights reflecting on the harbor, camellia flowers in foreground, cinematic, 16:9",
    zones: [
      { name: "시내 · 오동도", theme: "동백섬과 바다 위 케이블카, 포차의 밤" },
      { name: "돌산 · 향일암", theme: "해돋이 암자와 오션뷰 카페" }
    ],
    places: [
      { id:"odongdo", name:"오동도", cat:"spot", zone:0, slot:"am", lat:34.7435, lng:127.7669, stay:80,
        desc:"동백나무 3천 그루의 섬. 방파제 길을 걷거나 동백열차로 들어간다.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"오동도 입구 주차장(유료) — 섬 안은 차량 진입 불가, 도보 또는 동백열차" },
        ticket:{ note:"입장 무료 · 동백열차 왕복 1,000원대" }, wait:null },
      { id:"yeosucable", name:"여수해상케이블카", cat:"spot", zone:0, slot:"pm", lat:34.7420, lng:127.7659, stay:80,
        desc:"자산공원과 돌산공원을 잇는 바다 위 케이블카. 바닥이 투명한 크리스탈 캐빈이 인기.",
        fit:["couple","family","friends"],
        parking:{ ok:"hard", note:"자산탑승장 주차 협소 — 돌산탑승장 주차장이 넉넉" },
        ticket:{ note:"일반 캐빈 왕복 17,000원 · 크리스탈 24,000원 — 현장 발권, 온라인 소셜 할인 있음" },
        wait:{ note:"주말 오후·일몰 시간대 30분 이상 대기" } },
      { id:"leesunsin", name:"이순신광장 · 하멜등대", cat:"spot", zone:0, slot:"pm", lat:34.7367, lng:127.7405, stay:50,
        desc:"거북선 조형물과 바닷가 산책로. 종포해양공원까지 걷기 좋다.",
        fit:["family","solo","friends"],
        parking:{ ok:"hard", note:"광장 공영주차장(유료) — 저녁엔 포차거리와 공유라 혼잡" },
        ticket:null, wait:null },
      { id:"hwangso", name:"황소식당", cat:"food", zone:0, slot:"lunch", lat:34.7370, lng:127.7350, stay:60,
        desc:"간장게장·돌게장 백반의 대표 노포. 밥도둑 한 상.",
        fit:["family","couple","friends"],
        parking:{ ok:"hard", note:"전용 주차 없음 — 인근 공영주차장 이용" },
        ticket:null,
        wait:{ note:"주말 오픈런 필수 — 재료 소진 시 조기 마감" } },
      { id:"pocha", name:"낭만포차거리", cat:"food", zone:0, slot:"dinner", lat:34.7418, lng:127.7440, stay:90,
        desc:"종포해양공원의 밤바다 포차. 해물삼합과 딱새우회에 여수 밤바다를 곁들인다.",
        fit:["friends","couple"],
        parking:{ ok:"hard", note:"해양공원 공영주차장 저녁 만차 — 일찍 대거나 택시 추천" },
        ticket:null,
        wait:{ note:"금·토 저녁 인기 포차는 자리 대기 — 18시 전 도착 추천" } },
      { id:"rafique", name:"라피끄", cat:"cafe", zone:0, slot:"cafe", lat:34.7080, lng:127.7770, stay:60,
        desc:"돌산 바닷가의 대형 베이커리 카페. 통창 너머로 여수 바다가 가득.",
        fit:["couple","friends","family"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null, wait:{ note:"주말 오후 좌석 경쟁" } },
      { id:"hyangiram", name:"향일암", cat:"spot", zone:1, slot:"am", lat:34.5934, lng:127.8039, stay:90,
        desc:"바위 틈 계단을 지나 만나는 해돋이 암자. 남해가 발아래 펼쳐진다.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"입구 공영주차장(유료) — 암자까지 오르막 15분" },
        ticket:{ note:"입장 무료(2023년부터) · 일출 시간대 새벽 개방" },
        wait:{ note:"해돋이 명소라 연말연시·주말 새벽 혼잡" } },
      { id:"museulmok", name:"무슬목해변", cat:"spot", zone:1, slot:"pm", lat:34.6280, lng:127.7910, stay:40,
        desc:"몽돌이 구르는 소리가 좋은 해변. 돌산 드라이브 중간 쉼터.",
        fit:["couple","solo"],
        parking:{ ok:true, note:"해변 무료 주차장" },
        ticket:{ note:"무료" }, wait:null },
      { id:"moipin", name:"모이핀 여수돌산점", cat:"cafe", zone:1, slot:"cafe", lat:34.6220, lng:127.8010, stay:60,
        desc:"바다를 향해 열린 계단식 오션뷰 카페. 루프탑에서 남해 다도해가 보인다.",
        fit:["couple","friends"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null, wait:{ note:"주말 명당 좌석 경쟁 — 오전 방문 추천" } },
      { id:"gubaek", name:"구백식당", cat:"food", zone:1, slot:"lunch", lat:34.7378, lng:127.7345, stay:50,
        desc:"서대회무침의 원조 격. 새콤한 막걸리식초 양념에 밥을 비빈다.",
        fit:["family","solo","friends"],
        parking:{ ok:"hard", note:"전용 주차 없음 — 공영주차장 도보" },
        ticket:null,
        wait:{ note:"점심 대기 있음, 회전 빠름" } },
      { id:"dolsanpark", name:"돌산공원 야경", cat:"spot", zone:1, slot:"night", lat:34.7318, lng:127.7534, stay:50,
        desc:"돌산대교와 장군도, 여수 밤바다를 한눈에 담는 야경 포인트.",
        fit:["couple","friends"],
        parking:{ ok:true, note:"공원 주차장 보유" },
        ticket:{ note:"무료" }, wait:null }
    ]
  },

  /* ───────────────────────── 속초 ───────────────────────── */
  {
    id: "sokcho", name: "속초", en: "SOKCHO",
    tagline: "울산바위 아래 갯배를 타고, 물회 한 그릇의 바다",
    landmark: "설악산 · 아바이마을",
    maxDays: 2, speed: 480,
    artPrompt: "Ulsanbawi rock ridge of Seoraksan mountain towering over Sokcho harbor at golden hour, a small gaetbae ferry crossing the canal, red squid drying on lines, autumn colors, cinematic, 16:9",
    zones: [
      { name: "시내 · 아바이마을", theme: "갯배와 시장, 등대의 바다" },
      { name: "설악산 · 외옹치", theme: "케이블카로 오르는 바위산과 순두부 한 끼" }
    ],
    places: [
      { id:"yeonggeum", name:"영금정 · 속초등대전망대", cat:"spot", zone:0, slot:"am", lat:38.2119, lng:128.6003, stay:70,
        desc:"파도 소리가 거문고 같다는 정자와 등대 전망대. 동해 일출 명소.",
        fit:["family","couple","solo"],
        parking:{ ok:true, note:"동명항 공영주차장 이용" },
        ticket:{ note:"무료" }, wait:null },
      { id:"jungangsijang", name:"속초관광수산시장", cat:"food", zone:0, slot:"lunch", lat:38.2049, lng:128.5911, stay:80,
        desc:"만석닭강정과 씨앗호떡, 오징어순대의 시장. 먹거리 순례 코스.",
        fit:["family","friends"],
        parking:{ ok:true, note:"시장 공영주차타워(유료) — 주말 진입 정체" },
        ticket:null,
        wait:{ note:"만석닭강정 주말 30분 이상 줄 — 포장 주문 후 시장 구경 추천" } },
      { id:"abai", name:"아바이마을 · 갯배", cat:"spot", zone:0, slot:"pm", lat:38.2000, lng:128.5940, stay:70,
        desc:"줄을 당겨 건너는 갯배로 들어가는 실향민 마을. 아바이순대와 가을동화 촬영지.",
        fit:["family","couple","solo"],
        parking:{ ok:"hard", note:"마을 내 협소 — 시내 쪽에 대고 갯배로 건너기 추천" },
        ticket:{ note:"갯배 편도 500원 · 현장 승선" }, wait:null },
      { id:"chilsung", name:"칠성조선소", cat:"cafe", zone:0, slot:"cafe", lat:38.1963, lng:128.5866, stay:60,
        desc:"청초호의 옛 조선소를 개조한 카페·뮤지엄. 배 만들던 공간의 흔적이 그대로.",
        fit:["couple","friends","solo"],
        parking:{ ok:true, note:"전용 주차장 보유(협소) — 만차 시 청초호 공영" },
        ticket:null, wait:{ note:"주말 오후 좌석 대기" } },
      { id:"88gui", name:"88생선구이", cat:"food", zone:0, slot:"dinner", lat:38.2070, lng:128.5930, stay:70,
        desc:"모둠 생선구이 한 상. 자리에서 직원이 구워 주는 방식.",
        fit:["family","friends","couple"],
        parking:{ ok:"hard", note:"전용 주차 협소 — 동명항 공영주차장 도보" },
        ticket:null,
        wait:{ note:"저녁 대기 김 — 오픈 직후 방문 추천" } },
      { id:"sokchobeach", name:"속초해수욕장", cat:"spot", zone:0, slot:"pm", lat:38.1907, lng:128.6015, stay:50,
        desc:"시내에서 걸어가는 해변. 조형물 포토스팟과 해변 산책.",
        fit:["friends","couple","family"],
        parking:{ ok:true, note:"해변 공영주차장(성수기 유료)" },
        ticket:{ note:"무료" }, wait:null },
      { id:"seorak", name:"설악산 소공원 · 권금성 케이블카", cat:"spot", zone:1, slot:"am", lat:38.1735, lng:128.4899, stay:150,
        desc:"케이블카로 권금성 바위 능선까지. 신흥사 청동대불과 비룡폭포 코스도 이어진다.",
        fit:["family","couple","solo","friends"],
        parking:{ ok:true, note:"소공원 주차장(승용 5,000원) — 단풍철 새벽 만차" },
        ticket:{ note:"국립공원 입장(문화재구역) 무료화 · 케이블카 왕복 15,000원, 현장 발권 선착순 — 단풍철 오전 매진 잦음" },
        wait:{ note:"성수기 케이블카 1시간 이상 대기 — 개장 직후 발권 추천" } },
      { id:"sundubu", name:"김영애할머니순두부", cat:"food", zone:1, slot:"lunch", lat:38.2050, lng:128.5300, stay:60,
        desc:"학사평 순두부촌의 대표. 간수 대신 바닷물로 굳힌 초당식 순두부.",
        fit:["family","solo","couple"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null,
        wait:{ note:"주말 점심 대기 — 회전 빠른 편" } },
      { id:"git", name:"카페 긷", cat:"cafe", zone:1, slot:"cafe", lat:38.1950, lng:128.5450, stay:60,
        desc:"설악산을 마주 보는 미술관 같은 베이커리 카페. 중정의 소나무가 시그니처.",
        fit:["couple","solo"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null, wait:null },
      { id:"oeongchi", name:"외옹치 바다향기로", cat:"spot", zone:1, slot:"pm", lat:38.1840, lng:128.6070, stay:60,
        desc:"바다 절벽을 따라 놓인 데크 산책로. 45년간 닫혔던 해안 철책길.",
        fit:["couple","family","solo"],
        parking:{ ok:true, note:"외옹치항 공영주차장" },
        ticket:{ note:"무료 · 일몰 후 폐쇄" }, wait:null },
      { id:"bongpo", name:"봉포머구리집", cat:"food", zone:1, slot:"dinner", lat:38.2263, lng:128.5757, stay:70,
        desc:"해녀(머구리)가 잡은 해산물 물회. 전복·해삼 듬뿍 든 속초 대표 물회.",
        fit:["family","friends","couple"],
        parking:{ ok:true, note:"전용 주차장 보유" },
        ticket:null,
        wait:{ note:"식사 시간대 30분 내외 — 테이블링 원격 줄서기 지원" } }
    ]
  }
];

/* 준비 중인 지역 — 선택 시 가까운 추천 지역을 안내 */
const COMING_REGIONS = [
  { name: "인천 · 강화", near: "seoul" },
  { name: "춘천 · 가평", near: "seoul" },
  { name: "수원", near: "seoul" },
  { name: "양양 · 고성", near: "sokcho" },
  { name: "동해 · 삼척", near: "gangneung" },
  { name: "통영", near: "yeosu" },
  { name: "거제", near: "busan" },
  { name: "남해", near: "yeosu" },
  { name: "포항", near: "gyeongju" },
  { name: "안동", near: "gyeongju" },
  { name: "대구", near: "gyeongju" },
  { name: "군산", near: "jeonju" },
  { name: "담양 · 광주", near: "jeonju" },
  { name: "목포", near: "jeonju" },
  { name: "태안 · 안면도", near: "seoul" },
  { name: "단양 · 제천", near: "seoul" },
  { name: "서귀포", near: "jeju" }
];

/* 구성 옵션 */
const PARTY_TYPES = [
  { id: "solo", label: "혼자", sub: "나만의 속도로" },
  { id: "friends", label: "친구", sub: "먹고 걷고 떠들고" },
  { id: "couple", label: "연인", sub: "뷰와 분위기 위주" },
  { id: "family", label: "가족", sub: "주차 편한 동선" }
];
